
spring:
  application:
    name: testBackend
  datasource:
    url: jdbc:mysql://localhost:3306/hr?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
